<article>
	<h4>Contact</h4>
	<p>Lynda Williams</p>
	<p>
		<a href="mailto:lynda_williams@bcit.ca">Email</a> or text me at (778)-xxx-xxxx
	</p>
</article>

<article>
	<h4>Associated</h4>
	<ul>
		<li><a href="http://www.bcit.ca" target="_blank">BCIT</a></li>
		<li><a href="https://my.bcit.ca" target="_blank">my.bcit.ca</a></li>
		<li><a href="http://www.bcit.ca/study/outlines/20163033587" target="_blank">Course Outline</a></li>
		
	</ul>
</article>

<article>
	<h4>Meta Site</h4>
	<ul>
		<li><a href="/63dumm/final_project/" target="_blank">Introduction</li>
		<li><a href="/63dumm/final_project/proto_site/sitemap.html" target="_blank">Site Map</a></li>
		<li><a href="/63dumm/final_project/rationale.html" target="_blank">Rationale</li>
	</ul>
</article>