<h5>
	<i class="fa fa-wrench" aria-hidden="true"></i>
	Exercises <a href="javascript:void(0)" id="collapse-sidebar">&#10005;</a></h5>
<ul>
	<li>
		<a href="index.html">Exercise Home</a>
	</li>
	<li>
		<a href="exercise01.html">Exercise 01</a>
	</li>
	<!--
	<li>
		<a href="javascript:void(0)">Exercise 02</a>
	</li>
	<li>
		<a href="javascript:void(0)">Exercise 03</a>
	</li>
	<li>
		<a href="javascript:void(0)">Exercise 04</a>
	</li>
	<li>
		<a href="javascript:void(0)">Exercise 05</a>
	</li>
	<li>
		<a href="javascript:void(0)">Exercise 06</a>
	</li>
	<li>
		<a href="javascript:void(0)">Exercise 07</a>
	</li>
	<li>
		<a href="javascript:void(0)">Exercise 08</a>
	</li>
	<li>
		<a href="javascript:void(0)">Exercise 09</a>
	</li>
	-->
</ul>