<h5>
	<i class="fa fa-book" aria-hidden="true"></i>
	Lectures <a href="javascript:void(0)" id="collapse-sidebar">&#10005;</a></h5>
<ul>
	<li>
		<a href="index.html">Introduction</a>
	</li>
	<li>
		<a href="lecture01.html">Lecture 01</a>
	</li>
	<!--
	<li>
		<a href="javascript:void(0)">Lecture 02</a>
	</li>
	<li>
		<a href="javascript:void(0)">Lecture 03</a>
	</li>
	<li>
		<a href="javascript:void(0)">Lecture 04</a>
	</li>
	<li>
		<a href="javascript:void(0)">Lecture 05</a>
	</li>
	<li>
		<a href="javascript:void(0)">Lecture 06</a>
	</li>
	<li>
		<a href="javascript:void(0)">Lecture 07</a>
	</li>
	<li>
		<a href="javascript:void(0)">Lecture 08</a>
	</li>
	<li>
		<a href="javascript:void(0)">Lecture 09</a>
	</li>
	<li>
		<a href="javascript:void(0)">Lecture 10</a>
	</li>
	<li>
		<a href="javascript:void(0)">Lecture 11</a>
	</li>
	-->
</ul>