<ul>
	<li id="expand-sidebar">
		<a href="javascript:void(0)" title="Open the sidebar menu">&#9776;</a>
	</li>
	<li>
		<a href="/63dumm/final_project/proto_site">Home</a>
	</li>
	<li>
		<a href="/63dumm/final_project/proto_site/about">About</a>
	</li>
	<li>
		<a href="/63dumm/final_project/proto_site/lectures">Lectures</a>
	</li>
	<li>
		<a href="/63dumm/final_project/proto_site/exercises">Exercises</a>
	</li>
	<li>
		<a href="/63dumm/final_project/proto_site/quizzes">Quizzes</a>
	</li>
	<li>
		<a href="/63dumm/final_project/proto_site/resources">Resources</a>
	</li>
	<!--li class="dropdown right-float">
		<a class="dropbtn" href="#">Associated</a>
		<ul class="dropdown-content right-edge">
			<li>
				<a href="http://www.bcit.ca" target="_blank">BCIT</a>
			</li>
			<li>
				<a href="https://my.bcit.ca" target="_blank">my.bcit.ca</a>
			</li>
			<li>
				<a href="http://www.bcit.ca/study/outlines/20163033587" target="_blank">Course Outline</a>
			</li>
		</ul>
	</li-->
</ul>